import sys
import subprocess
import pytest

# Helper function to run the script as a separate process using subprocess
def run_survey_process(inputs):
    # Join inputs with newlines to simulate sequential user keystrokes
    input_data = "\n".join(inputs) + "\n"
    
    # Execute the target script using the current Python executable
    result = subprocess.run(
        [sys.executable, "lab1_SmartSurvey.py"],
        input=input_data,
        text=True,
        capture_output=True
    )
    # Return the standard output generated by the script
    return result.stdout

# 1. Test Tier 1: User is 18 or older and is a developer
def test_tier_1_admin_access():
    # Sequence: Name="Alice", Age="25", Developer="yes"
    inputs = ["Alice", "25", "yes"]
    output = run_survey_process(inputs)
    
    assert "Clearance tier is: Tier 1: Admin Infrastructure Access" in output

# 2. Test Tier 2: User is 18 or older but is not a developer
def test_tier_2_standard_access():
    # Sequence: Name="Bob", Age="30", Developer="no"
    inputs = ["Bob", "30", "no"]
    output = run_survey_process(inputs)
    
    assert "Clearance tier is: Tier 2: Standard Executive Access" in output

# 3. Test Tier 3: User is underage (Under 18)
def test_tier_3_guest_access():
    # Sequence: Name="Charlie", Age="16", Developer="yes"
    inputs = ["Charlie", "16", "yes"]
    output = run_survey_process(inputs)
    
    assert "Clearance tier is: Tier 3: Guest" in output

# 4. Test Error Handling: Script exits gracefully on invalid string age
def test_invalid_age_error():
    # Sequence: Name="Dave", Age="abc", Developer="no"
    inputs = ["Dave", "abc", "no"]
    output = run_survey_process(inputs)
    
    assert "Error: Enter valid age." in output

# 5. Test Error Handling: Script flags invalid developer status options
def test_invalid_dev_status():
    # Sequence: Name="Eve", Age="22", Developer="maybe"
    inputs = ["Eve", "22", "maybe"]
    output = run_survey_process(inputs)
    
    assert "Error: Enter valid developer status (Yes/No)" in output
